// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwogUSjn3nUqYFa6hRRcaxQmpcA4JlggM',
    appId: '1:715197497935:web:97cfdc85924b32514a603a',
    messagingSenderId: '715197497935',
    projectId: 'myfoodapp-de693',
    authDomain: 'myfoodapp-de693.firebaseapp.com',
    storageBucket: 'myfoodapp-de693.firebasestorage.app',
    measurementId: 'G-D2SXVTKDPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAyKrFTT25CNV620A926kesNze207povQ',
    appId: '1:715197497935:android:5ad7c42946a830ae4a603a',
    messagingSenderId: '715197497935',
    projectId: 'myfoodapp-de693',
    storageBucket: 'myfoodapp-de693.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAroDkWttJw8op_OMumWcOt1st2bBZgIw',
    appId: '1:715197497935:ios:c2f99c126f3cc8ef4a603a',
    messagingSenderId: '715197497935',
    projectId: 'myfoodapp-de693',
    storageBucket: 'myfoodapp-de693.firebasestorage.app',
    iosBundleId: 'com.example.myFoodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAroDkWttJw8op_OMumWcOt1st2bBZgIw',
    appId: '1:715197497935:ios:c2f99c126f3cc8ef4a603a',
    messagingSenderId: '715197497935',
    projectId: 'myfoodapp-de693',
    storageBucket: 'myfoodapp-de693.firebasestorage.app',
    iosBundleId: 'com.example.myFoodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwogUSjn3nUqYFa6hRRcaxQmpcA4JlggM',
    appId: '1:715197497935:web:efdb734d4556b2254a603a',
    messagingSenderId: '715197497935',
    projectId: 'myfoodapp-de693',
    authDomain: 'myfoodapp-de693.firebaseapp.com',
    storageBucket: 'myfoodapp-de693.firebasestorage.app',
    measurementId: 'G-LJF1G65B4K',
  );
}
